spring:
  profiles:
    active: local # default
    group:
      local: # local, common profile 을 그룹지어 함께 어플리케이션 구동
        - common
      prod: # local, prod profile 을 그룹지어 함께 어플리케이션 구동
        - common

---
spring:
  config:
    activate:
      on-profile: common


# ...

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
